### ISSUE TITLE
Last section (INSERT INTO) of sqlScript.sql script fails.

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyDeploymentGuide#1]
Required change:
"name" ---> "Name" and "muni" ---> "Municipality" for the Police Station', 'Museum And Archives' and 'Hospital' layers. - Airport is fine a is.

**Comment by iquitwow** [comment]
I noticed that when creating the guide.  Fixed now.  Thanks.
